---
language: node_js

notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install: ./scripts/ci/upgrade_docker_compose.sh

install: true

jobs:
  include:
    - stage: lint, build, and test
      script: ./scripts/ci/build.sh
    - stage: publish docker image
      if: branch = master
      script: ./scripts/ci/publish_docker_image.sh
